// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package graphql

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
)

type Gender string

const (
	GenderNa     Gender = "NA"
	GenderMale   Gender = "MALE"
	GenderFemale Gender = "FEMALE"
	GenderOther  Gender = "OTHER"
)

type SearchInput struct {
	Collections []*string `json:"collections"`
	Term        string    `json:"term"`
}

// GetCollections returns SearchInput.Collections, and is useful for accessing the field via an interface.
func (v *SearchInput) GetCollections() []*string { return v.Collections }

// GetTerm returns SearchInput.Term, and is useful for accessing the field via an interface.
func (v *SearchInput) GetTerm() string { return v.Term }

// SearchPeopleResponse is returned by SearchPeople on success.
type SearchPeopleResponse struct {
	Search *SearchPeopleSearchSearchResult `json:"search"`
}

// GetSearch returns SearchPeopleResponse.Search, and is useful for accessing the field via an interface.
func (v *SearchPeopleResponse) GetSearch() *SearchPeopleSearchSearchResult { return v.Search }

// SearchPeopleSearchSearchResult includes the requested fields of the GraphQL type SearchResult.
type SearchPeopleSearchSearchResult struct {
	Collections []SearchPeopleSearchSearchResultCollectionsSearchResultCollection `json:"collections"`
}

// GetCollections returns SearchPeopleSearchSearchResult.Collections, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResult) GetCollections() []SearchPeopleSearchSearchResultCollectionsSearchResultCollection {
	return v.Collections
}

// SearchPeopleSearchSearchResultCollectionsSearchResultCollection includes the requested fields of the GraphQL type SearchResultCollection.
type SearchPeopleSearchSearchResultCollectionsSearchResultCollection struct {
	Found int                                                                             `json:"found"`
	Hits  []*SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit `json:"-"`
}

// GetFound returns SearchPeopleSearchSearchResultCollectionsSearchResultCollection.Found, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollection) GetFound() int {
	return v.Found
}

// GetHits returns SearchPeopleSearchSearchResultCollectionsSearchResultCollection.Hits, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollection) GetHits() []*SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit {
	return v.Hits
}

func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollection) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*SearchPeopleSearchSearchResultCollectionsSearchResultCollection
		Hits []json.RawMessage `json:"hits"`
		graphql.NoUnmarshalJSON
	}
	firstPass.SearchPeopleSearchSearchResultCollectionsSearchResultCollection = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Hits
		src := firstPass.Hits
		*dst = make(
			[]*SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit,
			len(src))
		for i, src := range src {
			dst := &(*dst)[i]
			if len(src) != 0 && string(src) != "null" {
				*dst = new(SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit)
				err = __unmarshalSearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit(
					src, *dst)
				if err != nil {
					return fmt.Errorf(
						"unable to unmarshal SearchPeopleSearchSearchResultCollectionsSearchResultCollection.Hits: %w", err)
				}
			}
		}
	}
	return nil
}

type __premarshalSearchPeopleSearchSearchResultCollectionsSearchResultCollection struct {
	Found int `json:"found"`

	Hits []json.RawMessage `json:"hits"`
}

func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollection) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollection) __premarshalJSON() (*__premarshalSearchPeopleSearchSearchResultCollectionsSearchResultCollection, error) {
	var retval __premarshalSearchPeopleSearchSearchResultCollectionsSearchResultCollection

	retval.Found = v.Found
	{

		dst := &retval.Hits
		src := v.Hits
		*dst = make(
			[]json.RawMessage,
			len(src))
		for i, src := range src {
			dst := &(*dst)[i]
			if src != nil {
				var err error
				*dst, err = __marshalSearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit(
					src)
				if err != nil {
					return nil, fmt.Errorf(
						"unable to marshal SearchPeopleSearchSearchResultCollectionsSearchResultCollection.Hits: %w", err)
				}
			}
		}
	}
	return &retval, nil
}

// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit includes the requested fields of the GraphQL type AwardSearchHit.
type SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit struct {
	Typename *string `json:"__typename"`
}

// GetTypename returns SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit.Typename, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit) GetTypename() *string {
	return v.Typename
}

// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit includes the requested fields of the GraphQL type CompanySearchHit.
type SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit struct {
	Typename *string `json:"__typename"`
}

// GetTypename returns SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit.Typename, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit) GetTypename() *string {
	return v.Typename
}

// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit includes the requested fields of the GraphQL type GenreSearchHit.
type SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit struct {
	Typename *string `json:"__typename"`
}

// GetTypename returns SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit.Typename, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit) GetTypename() *string {
	return v.Typename
}

// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit includes the requested fields of the GraphQL type PersonSearchHit.
type SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit struct {
	Typename *string                                                                                   `json:"__typename"`
	Id       string                                                                                    `json:"id"`
	Name     string                                                                                    `json:"name"`
	Slug     string                                                                                    `json:"slug"`
	Person   *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPerson `json:"person"`
}

// GetTypename returns SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit.Typename, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit) GetTypename() *string {
	return v.Typename
}

// GetId returns SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit.Id, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit) GetId() string {
	return v.Id
}

// GetName returns SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit.Name, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit) GetName() string {
	return v.Name
}

// GetSlug returns SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit.Slug, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit) GetSlug() string {
	return v.Slug
}

// GetPerson returns SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit.Person, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit) GetPerson() *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPerson {
	return v.Person
}

// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPerson includes the requested fields of the GraphQL type Person.
type SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPerson struct {
	Headshot *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPersonHeadshotMedia `json:"headshot"`
	Bio      *string                                                                                                `json:"bio"`
	Gender   *Gender                                                                                                `json:"gender"`
}

// GetHeadshot returns SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPerson.Headshot, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPerson) GetHeadshot() *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPersonHeadshotMedia {
	return v.Headshot
}

// GetBio returns SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPerson.Bio, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPerson) GetBio() *string {
	return v.Bio
}

// GetGender returns SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPerson.Gender, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPerson) GetGender() *Gender {
	return v.Gender
}

// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPersonHeadshotMedia includes the requested fields of the GraphQL type Media.
// The GraphQL type's documentation follows.
//
// Simplified media type for public API responses (used in Work, Person, Article)
type SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPersonHeadshotMedia struct {
	Url               string  `json:"url"`
	ThumbnailImageUrl *string `json:"thumbnailImageUrl"`
}

// GetUrl returns SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPersonHeadshotMedia.Url, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPersonHeadshotMedia) GetUrl() string {
	return v.Url
}

// GetThumbnailImageUrl returns SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPersonHeadshotMedia.ThumbnailImageUrl, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHitPersonHeadshotMedia) GetThumbnailImageUrl() *string {
	return v.ThumbnailImageUrl
}

// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit includes the requested fields of the GraphQL interface SearchHit.
//
// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit is implemented by the following types:
// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit
// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit
// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit
// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit
// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit
// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit
type SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit interface {
	implementsGraphQLInterfaceSearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() *string
}

func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit) implementsGraphQLInterfaceSearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit() {
}
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit) implementsGraphQLInterfaceSearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit() {
}
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit) implementsGraphQLInterfaceSearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit() {
}
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit) implementsGraphQLInterfaceSearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit() {
}
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit) implementsGraphQLInterfaceSearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit() {
}
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit) implementsGraphQLInterfaceSearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit() {
}

func __unmarshalSearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit(b []byte, v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "AwardSearchHit":
		*v = new(SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit)
		return json.Unmarshal(b, *v)
	case "CompanySearchHit":
		*v = new(SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit)
		return json.Unmarshal(b, *v)
	case "GenreSearchHit":
		*v = new(SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit)
		return json.Unmarshal(b, *v)
	case "PersonSearchHit":
		*v = new(SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit)
		return json.Unmarshal(b, *v)
	case "UserSearchHit":
		*v = new(SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit)
		return json.Unmarshal(b, *v)
	case "WorkSearchHit":
		*v = new(SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing SearchHit.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit: "%v"`, tn.TypeName)
	}
}

func __marshalSearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit(v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit:
		typename = "AwardSearchHit"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit
		}{typename, v}
		return json.Marshal(result)
	case *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit:
		typename = "CompanySearchHit"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit
		}{typename, v}
		return json.Marshal(result)
	case *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit:
		typename = "GenreSearchHit"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit
		}{typename, v}
		return json.Marshal(result)
	case *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit:
		typename = "PersonSearchHit"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit
		}{typename, v}
		return json.Marshal(result)
	case *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit:
		typename = "UserSearchHit"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit
		}{typename, v}
		return json.Marshal(result)
	case *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit:
		typename = "WorkSearchHit"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit: "%T"`, v)
	}
}

// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit includes the requested fields of the GraphQL type UserSearchHit.
type SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit struct {
	Typename *string `json:"__typename"`
}

// GetTypename returns SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit.Typename, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit) GetTypename() *string {
	return v.Typename
}

// SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit includes the requested fields of the GraphQL type WorkSearchHit.
type SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit struct {
	Typename *string `json:"__typename"`
}

// GetTypename returns SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit.Typename, and is useful for accessing the field via an interface.
func (v *SearchPeopleSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit) GetTypename() *string {
	return v.Typename
}

// SearchWorksResponse is returned by SearchWorks on success.
type SearchWorksResponse struct {
	Search *SearchWorksSearchSearchResult `json:"search"`
}

// GetSearch returns SearchWorksResponse.Search, and is useful for accessing the field via an interface.
func (v *SearchWorksResponse) GetSearch() *SearchWorksSearchSearchResult { return v.Search }

// SearchWorksSearchSearchResult includes the requested fields of the GraphQL type SearchResult.
type SearchWorksSearchSearchResult struct {
	Collections []SearchWorksSearchSearchResultCollectionsSearchResultCollection `json:"collections"`
}

// GetCollections returns SearchWorksSearchSearchResult.Collections, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResult) GetCollections() []SearchWorksSearchSearchResultCollectionsSearchResultCollection {
	return v.Collections
}

// SearchWorksSearchSearchResultCollectionsSearchResultCollection includes the requested fields of the GraphQL type SearchResultCollection.
type SearchWorksSearchSearchResultCollectionsSearchResultCollection struct {
	Found int                                                                            `json:"found"`
	Hits  []*SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit `json:"-"`
}

// GetFound returns SearchWorksSearchSearchResultCollectionsSearchResultCollection.Found, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollection) GetFound() int {
	return v.Found
}

// GetHits returns SearchWorksSearchSearchResultCollectionsSearchResultCollection.Hits, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollection) GetHits() []*SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit {
	return v.Hits
}

func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollection) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*SearchWorksSearchSearchResultCollectionsSearchResultCollection
		Hits []json.RawMessage `json:"hits"`
		graphql.NoUnmarshalJSON
	}
	firstPass.SearchWorksSearchSearchResultCollectionsSearchResultCollection = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Hits
		src := firstPass.Hits
		*dst = make(
			[]*SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit,
			len(src))
		for i, src := range src {
			dst := &(*dst)[i]
			if len(src) != 0 && string(src) != "null" {
				*dst = new(SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit)
				err = __unmarshalSearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit(
					src, *dst)
				if err != nil {
					return fmt.Errorf(
						"unable to unmarshal SearchWorksSearchSearchResultCollectionsSearchResultCollection.Hits: %w", err)
				}
			}
		}
	}
	return nil
}

type __premarshalSearchWorksSearchSearchResultCollectionsSearchResultCollection struct {
	Found int `json:"found"`

	Hits []json.RawMessage `json:"hits"`
}

func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollection) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollection) __premarshalJSON() (*__premarshalSearchWorksSearchSearchResultCollectionsSearchResultCollection, error) {
	var retval __premarshalSearchWorksSearchSearchResultCollectionsSearchResultCollection

	retval.Found = v.Found
	{

		dst := &retval.Hits
		src := v.Hits
		*dst = make(
			[]json.RawMessage,
			len(src))
		for i, src := range src {
			dst := &(*dst)[i]
			if src != nil {
				var err error
				*dst, err = __marshalSearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit(
					src)
				if err != nil {
					return nil, fmt.Errorf(
						"unable to marshal SearchWorksSearchSearchResultCollectionsSearchResultCollection.Hits: %w", err)
				}
			}
		}
	}
	return &retval, nil
}

// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit includes the requested fields of the GraphQL type AwardSearchHit.
type SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit struct {
	Typename *string `json:"__typename"`
}

// GetTypename returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit.Typename, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit) GetTypename() *string {
	return v.Typename
}

// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit includes the requested fields of the GraphQL type CompanySearchHit.
type SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit struct {
	Typename *string `json:"__typename"`
}

// GetTypename returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit.Typename, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit) GetTypename() *string {
	return v.Typename
}

// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit includes the requested fields of the GraphQL type GenreSearchHit.
type SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit struct {
	Typename *string `json:"__typename"`
}

// GetTypename returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit.Typename, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit) GetTypename() *string {
	return v.Typename
}

// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit includes the requested fields of the GraphQL type PersonSearchHit.
type SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit struct {
	Typename *string `json:"__typename"`
}

// GetTypename returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit.Typename, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit) GetTypename() *string {
	return v.Typename
}

// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit includes the requested fields of the GraphQL interface SearchHit.
//
// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit is implemented by the following types:
// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit
// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit
// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit
// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit
// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit
// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit
type SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit interface {
	implementsGraphQLInterfaceSearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() *string
}

func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit) implementsGraphQLInterfaceSearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit() {
}
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit) implementsGraphQLInterfaceSearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit() {
}
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit) implementsGraphQLInterfaceSearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit() {
}
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit) implementsGraphQLInterfaceSearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit() {
}
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit) implementsGraphQLInterfaceSearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit() {
}
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit) implementsGraphQLInterfaceSearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit() {
}

func __unmarshalSearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit(b []byte, v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "AwardSearchHit":
		*v = new(SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit)
		return json.Unmarshal(b, *v)
	case "CompanySearchHit":
		*v = new(SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit)
		return json.Unmarshal(b, *v)
	case "GenreSearchHit":
		*v = new(SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit)
		return json.Unmarshal(b, *v)
	case "PersonSearchHit":
		*v = new(SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit)
		return json.Unmarshal(b, *v)
	case "UserSearchHit":
		*v = new(SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit)
		return json.Unmarshal(b, *v)
	case "WorkSearchHit":
		*v = new(SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing SearchHit.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit: "%v"`, tn.TypeName)
	}
}

func __marshalSearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit(v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit:
		typename = "AwardSearchHit"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsAwardSearchHit
		}{typename, v}
		return json.Marshal(result)
	case *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit:
		typename = "CompanySearchHit"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsCompanySearchHit
		}{typename, v}
		return json.Marshal(result)
	case *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit:
		typename = "GenreSearchHit"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsGenreSearchHit
		}{typename, v}
		return json.Marshal(result)
	case *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit:
		typename = "PersonSearchHit"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsPersonSearchHit
		}{typename, v}
		return json.Marshal(result)
	case *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit:
		typename = "UserSearchHit"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit
		}{typename, v}
		return json.Marshal(result)
	case *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit:
		typename = "WorkSearchHit"

		result := struct {
			TypeName string `json:"__typename"`
			*SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsSearchHit: "%T"`, v)
	}
}

// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit includes the requested fields of the GraphQL type UserSearchHit.
type SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit struct {
	Typename *string `json:"__typename"`
}

// GetTypename returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit.Typename, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsUserSearchHit) GetTypename() *string {
	return v.Typename
}

// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit includes the requested fields of the GraphQL type WorkSearchHit.
type SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit struct {
	Typename *string                                                                              `json:"__typename"`
	Id       string                                                                               `json:"id"`
	Title    string                                                                               `json:"title"`
	Slug     string                                                                               `json:"slug"`
	Work     *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork `json:"work"`
}

// GetTypename returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit.Typename, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit) GetTypename() *string {
	return v.Typename
}

// GetId returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit.Id, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit) GetId() string {
	return v.Id
}

// GetTitle returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit.Title, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit) GetTitle() string {
	return v.Title
}

// GetSlug returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit.Slug, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit) GetSlug() string {
	return v.Slug
}

// GetWork returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit.Work, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHit) GetWork() *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork {
	return v.Work
}

// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork includes the requested fields of the GraphQL type Work.
// The GraphQL type's documentation follows.
//
// Represents a work (e.g., movie, series, documentary) in the system.
type SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork struct {
	// The type of work (e.g., movie, series, documentary, short film).
	WorkType WorkType `json:"workType"`
	// The year the work was released.
	ReleaseYear *int `json:"releaseYear"`
	// The date the work was released in theaters or made available for streaming.
	ReleaseDate *string `json:"releaseDate"`
	// The media asset used as the poster image for the work.
	Poster *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWorkPosterMedia `json:"poster"`
	// List of genres associated with the work.
	Genres []SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWorkGenresGenre `json:"genres"`
	// Duration of the work in minutes.
	Runtime *int `json:"runtime"`
	// A brief description of the work.
	Summary *string `json:"summary"`
	// A detailed synopsis of the work.
	Synopsis *string `json:"synopsis"`
}

// GetWorkType returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork.WorkType, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork) GetWorkType() WorkType {
	return v.WorkType
}

// GetReleaseYear returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork.ReleaseYear, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork) GetReleaseYear() *int {
	return v.ReleaseYear
}

// GetReleaseDate returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork.ReleaseDate, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork) GetReleaseDate() *string {
	return v.ReleaseDate
}

// GetPoster returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork.Poster, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork) GetPoster() *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWorkPosterMedia {
	return v.Poster
}

// GetGenres returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork.Genres, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork) GetGenres() []SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWorkGenresGenre {
	return v.Genres
}

// GetRuntime returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork.Runtime, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork) GetRuntime() *int {
	return v.Runtime
}

// GetSummary returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork.Summary, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork) GetSummary() *string {
	return v.Summary
}

// GetSynopsis returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork.Synopsis, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWork) GetSynopsis() *string {
	return v.Synopsis
}

// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWorkGenresGenre includes the requested fields of the GraphQL type Genre.
type SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWorkGenresGenre struct {
	Name string `json:"name"`
}

// GetName returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWorkGenresGenre.Name, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWorkGenresGenre) GetName() string {
	return v.Name
}

// SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWorkPosterMedia includes the requested fields of the GraphQL type Media.
// The GraphQL type's documentation follows.
//
// Simplified media type for public API responses (used in Work, Person, Article)
type SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWorkPosterMedia struct {
	Url               string  `json:"url"`
	ThumbnailImageUrl *string `json:"thumbnailImageUrl"`
}

// GetUrl returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWorkPosterMedia.Url, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWorkPosterMedia) GetUrl() string {
	return v.Url
}

// GetThumbnailImageUrl returns SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWorkPosterMedia.ThumbnailImageUrl, and is useful for accessing the field via an interface.
func (v *SearchWorksSearchSearchResultCollectionsSearchResultCollectionHitsWorkSearchHitWorkPosterMedia) GetThumbnailImageUrl() *string {
	return v.ThumbnailImageUrl
}

// Type of work (for WORKS category requests)
type WorkType string

const (
	WorkTypeMovie       WorkType = "MOVIE"
	WorkTypeTvShow      WorkType = "TV_SHOW"
	WorkTypeWebSeries   WorkType = "WEB_SERIES"
	WorkTypeEpisode     WorkType = "EPISODE"
	WorkTypeDocumentary WorkType = "DOCUMENTARY"
	WorkTypeMusicVideo  WorkType = "MUSIC_VIDEO"
	WorkTypeShortFilm   WorkType = "SHORT_FILM"
	WorkTypePodcast     WorkType = "PODCAST"
	WorkTypeOther       WorkType = "OTHER"
)

// __SearchPeopleInput is used internally by genqlient
type __SearchPeopleInput struct {
	Input SearchInput `json:"input"`
}

// GetInput returns __SearchPeopleInput.Input, and is useful for accessing the field via an interface.
func (v *__SearchPeopleInput) GetInput() SearchInput { return v.Input }

// __SearchWorksInput is used internally by genqlient
type __SearchWorksInput struct {
	Input SearchInput `json:"input"`
}

// GetInput returns __SearchWorksInput.Input, and is useful for accessing the field via an interface.
func (v *__SearchWorksInput) GetInput() SearchInput { return v.Input }

// The query or mutation executed by SearchPeople.
const SearchPeople_Operation = `
query SearchPeople ($input: SearchInput!) {
	search(input: $input) {
		collections {
			found
			hits {
				__typename
				... on PersonSearchHit {
					id
					name
					slug
					person {
						headshot {
							url
							thumbnailImageUrl
						}
						bio
						gender
					}
				}
			}
		}
	}
}
`

func SearchPeople(
	ctx_ context.Context,
	client_ graphql.Client,
	input SearchInput,
) (*SearchPeopleResponse, error) {
	req_ := &graphql.Request{
		OpName: "SearchPeople",
		Query:  SearchPeople_Operation,
		Variables: &__SearchPeopleInput{
			Input: input,
		},
	}
	var err_ error

	var data_ SearchPeopleResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by SearchWorks.
const SearchWorks_Operation = `
query SearchWorks ($input: SearchInput!) {
	search(input: $input) {
		collections {
			found
			hits {
				__typename
				... on WorkSearchHit {
					id
					title
					slug
					work {
						workType
						releaseYear
						releaseDate
						poster {
							url
							thumbnailImageUrl
						}
						genres {
							name
						}
						runtime
						summary
						synopsis
					}
				}
			}
		}
	}
}
`

func SearchWorks(
	ctx_ context.Context,
	client_ graphql.Client,
	input SearchInput,
) (*SearchWorksResponse, error) {
	req_ := &graphql.Request{
		OpName: "SearchWorks",
		Query:  SearchWorks_Operation,
		Variables: &__SearchWorksInput{
			Input: input,
		},
	}
	var err_ error

	var data_ SearchWorksResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
